name: dio_client
description: A simplified DIO implementation.
version: 0.0.1+1
homepage: https://github.com/mkhtradm01/dio_client

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  very_good_analysis: ^3.0.1

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
