name: dio_client
description: A simplified[Dio](https://pub.dev/packages/dio) implementation, it targets junior developers that need to quickly have http implementation in their applications.
version: 0.0.1+2
homepage: https://github.com/mkhtradm01/dio_client

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  very_good_analysis: ^3.0.1

platforms:
  android:
  ios:
  web:
  macos:
  windows:

dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
